Docs and guides for `--use-wallet`
r0gue-io/pop-docs pull request #16
Opened 2024-12-18 02:27 UTC by peterwht

2024-12-18 02:32 UTC, peterwht commented
[sc-1779]

2024-12-18 10:14 UTC, al3mart commented on pop-cli-for-smart-contracts/.gitbook/assets/use-wallet/connect-wallet.png
We could substitute with a screen shot showing many more wallets!

Gave a heads up to @AlexD10S as he already has this.

2024-12-18 10:14 UTC, al3mart commented on pop-cli-for-smart-contracts/guides/securely-sign-transactions-from-cli.md
> +Normally, you would provide `--suri=<private-key>` to deploy the contract. However, this should only be used for development accounts.
I feel we should append something at the end here mentioning that this implies insecure handling of secretes.

2024-12-18 10:26 UTC, al3mart commented on pop-cli-for-smart-contracts/guides/securely-sign-transactions-from-cli.md
> +Normally, you would provide `--suri=<private-key>` to deploy the contract. However, this should only be used for development accounts.
https://github.com/r0gue-io/pop-docs/pull/17

2024-12-18 12:03 UTC, AlexD10S commented on pop-cli-for-smart-contracts/.gitbook/assets/use-wallet/connect-wallet.png
<img width="647" alt="Captura de pantalla 2024-12-18 a las 12 49 03" src="https://github.com/user-attachments/assets/d3b97ddb-aee9-4708-b5db-9276f3c4aaa9" />

2024-12-18 16:03 UTC, AlexD10S reviewed
Looks good! 
I included a brief comment about wallet integration in the parachain onboarding docs.

Also as suggested by Ale here: https://github.com/r0gue-io/pop-docs/pull/16#discussion_r1889969779 I updated image to show all wallets, but feel free to pick the one you prefer.

2024-12-18 19:26 UTC, AlexD10S approved these changes
Looks good to me!

2024-12-18 23:40 UTC, evilrobot-01 commented on pop-cli-for-smart-contracts/guides/securely-sign-transactions-from-cli.md
> +Note that for contract calls, the portal will perform a dry-run to alert if the transaction will succeed, and also estimate the gas costs.
```suggestion
Note that for contract calls, the portal will perform a dry-run to alert you if the transaction will succeed, and also estimate the gas costs.
```

2024-12-18 23:42 UTC, evilrobot-01 commented on pop-cli-for-smart-contracts/guides/securely-sign-transactions-from-cli.md
> +Once ready to sign, pressing the `Sign` button will open your wallet for signature.
```suggestion
Once ready to sign, pressing the `Submit` button will open your wallet for signature.
```

2024-12-18 23:43 UTC, evilrobot-01 commented on pop-cli-for-appchains/guides/securely-sign-transactions-from-cli.md
> +Once ready to sign, pressing the `Sign` button will open your wallet for signature.
```suggestion
Once ready to sign, pressing the `Submit` button will open your wallet for signature.
```

2024-12-18 23:46 UTC, evilrobot-01 requested changes
Just three quick fixes please and then good to approve.

2024-12-19 08:48 UTC, evilrobot-01 approved these changes
Looks good, thank you!

2024-12-19 09:06 UTC, merged